import type { Course, Quiz, Group, Settings, User } from './types';
import bcrypt from 'bcryptjs';

export const initialCourses: Omit<Course, 'id'>[] = [
  {
    title: 'أساسيات الفيزياء - المرحلة الثانوية',
    description: 'كورس شامل لشرح أساسيات الفيزياء للصف الثالث الثانوي يغطي كل فصول المنهج بطريقة مبسطة مع أمثلة محلولة.',
    category: 'فيزياء',
    price: 299,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
    rating: 4.8,
    studentsCount: 1240,
    duration: 1800,
    lessons: [
      { id: 'l1', title: 'مقدمة في علم الفيزياء', description: 'نظرة عامة على علم الفيزياء وأهميته', duration: 25, isFree: true },
      { id: 'l2', title: 'الكميات الفيزيائية ووحدات القياس', description: 'شرح الكميات الأساسية والمشتقة', duration: 40, isFree: false },
      { id: 'l3', title: 'المتجهات', description: 'جمع وطرح المتجهات وتحليلها', duration: 45, isFree: false },
      { id: 'l4', title: 'الحركة في خط مستقيم', description: 'السرعة والتسارع ومعادلات الحركة', duration: 50, isFree: false },
      { id: 'l5', title: 'قوانين نيوتن للحركة', description: 'القانون الأول والثاني والثالث', duration: 55, isFree: false },
    ],
  },
  {
    title: 'الرياضيات - التفاضل والتكامل',
    description: 'شرح كامل لوحدة التفاضل والتكامل للثانوية العامة مع حل جميع تمارين الكتاب المدرسي.',
    category: 'رياضيات',
    price: 349,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&q=80',
    rating: 4.9,
    studentsCount: 2150,
    duration: 2400,
    lessons: [
      { id: 'l6', title: 'النهايات', description: 'مفهوم النهاية وطرق حسابها', duration: 35, isFree: true },
      { id: 'l7', title: 'اتصال الدالة', description: 'شروط اتصال الدالة عند نقطة', duration: 30, isFree: false },
      { id: 'l8', title: 'مشتقة الدالة', description: 'تعريف المشتقة وقواعد الاشتقاق', duration: 45, isFree: false },
      { id: 'l9', title: 'تطبيقات المشتقة', description: 'النهايات العظمى والصغرى', duration: 50, isFree: false },
    ],
  },
  {
    title: 'الكيمياء العضوية',
    description: 'كورس متكامل في الكيمياء العضوية يبدأ من الصفر حتى الاحتراف مع شرح تفاعلات المركبات العضوية.',
    category: 'كيمياء',
    price: 0,
    isFree: true,
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80',
    rating: 4.6,
    studentsCount: 980,
    duration: 1200,
    lessons: [
      { id: 'l10', title: 'مقدمة الكيمياء العضوية', description: 'نظرة تاريخية وأهمية الكيمياء العضوية', duration: 30, isFree: true },
      { id: 'l11', title: 'الهيدروكربونات', description: 'الألكانات والألكينات والألكاينات', duration: 40, isFree: true },
      { id: 'l12', title: 'المجموعات الوظيفية', description: 'الكحولات والأحماض والإسترات', duration: 50, isFree: true },
    ],
  },
  {
    title: 'الأحياء - الخلية والوراثة',
    description: 'شرح وحدتي الخلية والوراثة مع رسومات توضيحية ومقاطع مجهرية.',
    category: 'أحياء',
    price: 249,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&q=80',
    rating: 4.7,
    studentsCount: 1560,
    duration: 1500,
    lessons: [
      { id: 'l13', title: 'تركيب الخلية', description: 'الخلية بدائية وحقيقية النواة', duration: 35, isFree: true },
      { id: 'l14', title: 'انقسام الخلية', description: 'الانقسام الميتوزي والميوزي', duration: 45, isFree: false },
      { id: 'l15', title: 'الـ DNA والـ RNA', description: 'التركيب والوظيفة', duration: 50, isFree: false },
      { id: 'l16', title: 'قوانين مندل', description: 'الصفات السائدة والمتنحية', duration: 40, isFree: false },
    ],
  },
  {
    title: 'اللغة الإنجليزية - قواعد ومحادثة',
    description: 'كورس شامل لتعلم قواعد اللغة الإنجليزية وتطوير مهارة المحادثة من المستوى المبتدئ للمتقدم.',
    category: 'إنجليزي',
    price: 199,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&q=80',
    rating: 4.5,
    studentsCount: 3200,
    duration: 2000,
    lessons: [
      { id: 'l17', title: 'Present Simple', description: 'الاستخدام والقواعد', duration: 25, isFree: true },
      { id: 'l18', title: 'Past Simple', description: 'زمن الماضي البسيط', duration: 30, isFree: false },
      { id: 'l19', title: 'Conversation Basics', description: 'جمل المحادثة الأساسية', duration: 35, isFree: false },
    ],
  },
  {
    title: 'الفيزياء - الكهرباء والمغناطيسية',
    description: 'شرح وحدتي الكهرباء والمغناطيسية مع تجارب توضيحية ومسائل محلولة.',
    category: 'فيزياء',
    price: 279,
    isFree: false,
    image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    rating: 4.9,
    studentsCount: 890,
    duration: 1400,
    lessons: [
      { id: 'l20', title: 'الشحنة الكهربائية', description: 'مفهوم الشحنة وقانون كولوم', duration: 30, isFree: true },
      { id: 'l21', title: 'المجال الكهربائي', description: 'خطوط المجال وشدة المجال', duration: 40, isFree: false },
      { id: 'l22', title: 'التيار الكهربائي', description: 'قانون أوم والمقاومة', duration: 45, isFree: false },
    ],
  },
];

export const initialQuizzes: Omit<Quiz, 'id'>[] = [
  {
    title: 'اختبار الفيزياء - المتجهات والحركة',
    description: 'اختبار شامل على دروس المتجهات والحركة في خط مستقيم.',
    courseId: 'c1',
    duration: 20,
    passingScore: 60,
    questions: [
      {
        id: 'q1',
        text: 'ما هي وحدة قياس السرعة في النظام الدولي؟',
        type: 'multiple',
        options: ['م/ث', 'كجم/م', 'م/ث²', 'نيوتن'],
        correctAnswer: 'م/ث',
        points: 10,
      },
      {
        id: 'q2',
        text: 'السرعة كمية قياسية.',
        type: 'truefalse',
        options: ['صواب', 'خطأ'],
        correctAnswer: 'خطأ',
        points: 10,
      },
      {
        id: 'q3',
        text: 'إذا كانت السرعة الابتدائية لجسم 10 م/ث والتسارع 2 م/ث² لمدة 5 ثواني، فما السرعة النهائية؟',
        type: 'multiple',
        options: ['15 م/ث', '20 م/ث', '25 م/ث', '30 م/ث'],
        correctAnswer: '20 م/ث',
        points: 15,
      },
      {
        id: 'q4',
        text: 'التسارع هو معدل تغير السرعة بالنسبة للزمن.',
        type: 'truefalse',
        options: ['صواب', 'خطأ'],
        correctAnswer: 'صواب',
        points: 10,
      },
    ],
  },
  {
    title: 'اختبار الرياضيات - النهايات والمشتقات',
    description: 'اختبار على النهايات ومشتقات الدوال.',
    courseId: 'c2',
    duration: 25,
    passingScore: 50,
    questions: [
      {
        id: 'q5',
        text: 'ما هي مشتقة الدالة f(x) = x² ؟',
        type: 'multiple',
        options: ['x', '2x', '2', 'x²'],
        correctAnswer: '2x',
        points: 10,
      },
      {
        id: 'q6',
        text: 'نهاية الدالة (sin x)/x عندما x تؤول للصفر تساوي صفر.',
        type: 'truefalse',
        options: ['صواب', 'خطأ'],
        correctAnswer: 'خطأ',
        points: 10,
      },
      {
        id: 'q7',
        text: 'مشتقة الدالة الثابتة تساوي:',
        type: 'multiple',
        options: ['الثابت نفسه', 'صفر', 'واحد', 'غير معرّفة'],
        correctAnswer: 'صفر',
        points: 10,
      },
    ],
  },
  {
    title: 'اختبار الكيمياء - الهيدروكربونات',
    description: 'اختبار على الهيدروكربونات.',
    courseId: 'c3',
    duration: 15,
    passingScore: 70,
    questions: [
      {
        id: 'q8',
        text: 'الألكانات تحتوي على روابط أحادية فقط.',
        type: 'truefalse',
        options: ['صواب', 'خطأ'],
        correctAnswer: 'صواب',
        points: 10,
      },
      {
        id: 'q9',
        text: 'ما هو الصيغة العامة للألكانات؟',
        type: 'multiple',
        options: ['CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnHn'],
        correctAnswer: 'CnH2n+2',
        points: 15,
      },
    ],
  },
];

export const initialGroups: Omit<Group, 'id'>[] = [
  { name: 'مجموعة الفيزياء - الصف الثالث الثانوي', courseId: 'c1' },
  { name: 'مجموعة الرياضيات - عامة' },
  { name: 'مجموعة الكيمياء العضوية', courseId: 'c3' },
  { name: 'مجموعة الأحياء' },
  { name: 'مجموعة اللغة الإنجليزية' },
];

export const initialSettings: Settings = {
  platformName: 'منصتي',
  description: 'منصة تعليمية متكاملة للطالب المصري - مع الأستاذ أحمد محمد',
  email: 'info@mansati.com',
  phone: '01012345678',
  facebook: 'https://facebook.com/mansati',
  youtube: 'https://youtube.com/@mansati',
  telegram: 'https://t.me/mansati',
  monthlyPrice: 49,
  yearlyPrice: 449,
  emailNotifications: true,
  pushNotifications: true,
  newCourseAlerts: true,
};

export async function getSeedUsers(): Promise<User[]> {
  return [
    {
      id: 'admin1',
      name: 'الأستاذ أحمد محمد',
      email: 'admin@mansati.com',
      phone: '01000000000',
      password: await bcrypt.hash('admin123', 10),
      role: 'admin',
      points: 0,
      createdAt: new Date().toISOString(),
      status: 'active',
    },
  ];
}
